config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :devices, only: [:new, :create, :destroy]

  patch 'goals', to: 'goals#update', as: 'goals'
  resources :goals, only: [:index, :new, :create, :destroy]

  resources :tiers, only: [:index]
  resources :rankings, only: [:index]

  get "profile", to: "data_points#index"
  get 'auth/fitbit_oauth2/callback', to: 'devices#callback'
  # get 'userdevice/fitbit_oauth2/callback', to: 'devices#callback'
  get 'graph', to: 'pages#graph'
  get 'gontest', to: 'pages#gontest'
  get 'test', to: 'pages#test'

  get 'premium/upgrade/payments', to: 'payments#new'
  post 'premium/upgrade/payments', to: 'payments#create'

  root to: 'pages#home'
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1>Le Wagon Berlin</h1>
    <p>Learn to code with us in Berlin</p>
    <a class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="flexbox-footer" style="padding-top: 100px;">
      <div class="footer-category">
        <h3 style="color:white; border-bottom: 1px solid hsla(0,0%,55%,.5);">Legal</h3>
        <p>
           Terms
        </p>
        <p>
            Privacy
        </p>
        <p>
            Imprint
        </p>
      </div>
      <div class="footer-category">
        <h3 style="color:white; border-bottom: 1px solid hsla(0,0%,55%,.5);">Support</h3>
        <p>
           Help & Support
        </p>
        <p>
            Knowledge
        </p>
        <p>
            Blog
        </p>
      </div>
      <div class="footer-category">
        <h3 style="color:white; border-bottom: 1px solid hsla(0,0%,55%,.5);">Find us</h3>
        <div class="find-us">
                  <p>
                 Stackle, 2 Avenue des Saules,  Lille, FRANCE
              </p>
              <p>
                  info@stackle.com
              </p>
              <p>
                  +33 945 674 545
              </p>
              </div>
      </div>
    </div>
    <div class="text-center" style="padding-top: 70px; padding-bottom: 20px;">
     <p id="stakle">Copyright STAKLE© 2018 All right reserved.</p>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<% if current_user %>
  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>
    <div class="form-inputs">
      <div class="opacity-0">
        <%= f.input :photo, label: false %>
        <%= f.input :photo_cache, as: :hidden, label: false %>
      </div>
      <div class="row">
        <div class="col-12 col-sm-6">
          <label for="first_name"><i class="far fa-user pr-1 mr-2"></i>First name</label>
          <%= f.input :first_name, label: false, required: false, autofocus: true %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="far fa-user pr-1 mr-2"></i>Last name</label>
          <%= f.input :last_name, label: false, required: false, autofocus: true, class: "far fa-weight" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="fas fa-at pr-1 mr-2"></i>Pseudo</label>
          <%= f.input :pseudo, label: false, required: true, autofocus: true %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="fas fa-at pr-1 mr-2"></i>Mail</label>
          <%= f.input :email, label: false, required: true, autofocus: true %>
          <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
          <% end %>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-12 col-sm-4 small-font opacity">
          <label for=":weight"><i class="fas fa-arrows-alt-v mr-1"></i>(cm)</label>
          <%= f.input :height, label: false, required: false, autofocus: true %>
        </div>
        <div class="col-12 col-sm-4 small-font opacity">
          <label for=":weight"><i class="fas fa-weight mr-2"></i>(kg)</label>
          <%= f.input :weight, label: false, required: false, autofocus: true %>
        </div>
        <div class="col-12 col-sm-4 small-font opacity">
          <label for=":weight"><i class="fas fa-birthday-cake"></i></label>
          <%= f.input :birthday, label: false, required: false, autofocus: true %>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <p><i class="fas fa-key pr-1 mr-2"></i>Change your password</p>
        </div>
      </div>
      <% if current_user %>
      <div class="row small-font opacity">
        <div class="col-12 col-sm-4">
          <label for=":weight">current password</label>
          <%= f.input :current_password, label: false, required: true %>
        </div>
        <div class="col-12 col-sm-4">
        <label for=":weight">new password</label>
          <%= f.input :password, label: false, required: false %>
        </div>
        <div class="col-12 col-sm-4">
          <label for=":password_confirmation">confirm new password</label>
          <%= f.input :password_confirmation, autocomplete: "off", label: false, required: false %>
        </div>
      </div>
      <% else %>
      <div class="row small-font opacity">
        <div class="col-12 col-sm-4">
        <label for=":weight">password</label>
          <%= f.input :password, label: false, required: false %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":password_confirmation">confirm new password</label>
          <%= f.input :password_confirmation, autocomplete: "off", label: false, required: false %>
        </div>
      </div>
      <% end %>
    </div>

    <%  if current_user %>
      <div class="form-actions text-center">
        <%= f.button :submit, 'Update', class: 'btn btn-primary btn-update' %>
      </div>
      <div class="text-center">
        <br>
        Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
      </div>
    <% else %>
      <div class="form-actions text-right">
        <%= f.button :submit, 'Sign up', class: 'btn btn-primary btn-form' %>
        <br>
        <%= render "devise/shared/links" %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>
    <div class="form-inputs">
      <div class="opacity-0">
        <%= f.input :photo, label: false %>
        <%= f.input :photo_cache, as: :hidden, label: false %>
      </div>
      <div class="row">
        <div class="col-12 col-sm-6">
          <label for="first_name"><i class="far fa-user pr-1 mr-2"></i>First name</label>
          <%= f.input :first_name, label: false, required: false, autofocus: true %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="far fa-user pr-1 mr-2"></i>Last name</label>
          <%= f.input :last_name, label: false, required: false, autofocus: true, class: "far fa-weight" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="fas fa-at pr-1 mr-2"></i>Pseudo</label>
          <%= f.input :pseudo, label: false, required: true, autofocus: true %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":weight"><i class="fas fa-at pr-1 mr-2"></i>Mail</label>
          <%= f.input :email, label: false, required: true, autofocus: true %>
          <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
          <% end %>
        </div>
      </div>
      <!-- <div class="row text-center"> -->
<!--         <div class="col-12 col-sm-4 small-font opacity"> -->
<!--           <label for=":weight"><i class="fas fa-map-marker-alt mr-1"></i>(m)</label> -->
<!--           <%= f.input :height, label: false, required: false, autofocus: true %> -->
<!--         </div> -->
<!--         <div class="col-12 col-sm-4 small-font opacity"> -->
<!--           <label for=":weight"><i class="fas fa-weight mr-2"></i>(kg)</label> -->
<!--           <%= f.input :weight, label: false, required: false, autofocus: true %> -->
<!--         </div> -->
<!--         <div class="col-12 col-sm-4 small-font opacity"> -->
<!--           <label for=":weight"><i class="fas fa-birthday-cake"></i></label> -->
<!--           <%= f.input :birthday, label: false, required: false, autofocus: true %> -->
<!--         </div> -->
<!--       </div> -->
      <div class="row">
        <div class="col-12">
          <p><i class="fas fa-key pr-1 mr-2"></i>Change your password</p>
        </div>
      </div>
      <% if current_user %>
      <div class="row small-font opacity">
        <div class="col-12 col-sm-4">
          <label for=":weight">current password</label>
          <%= f.input :current_password, label: false, required: true %>
        </div>
        <div class="col-12 col-sm-4">
        <label for=":weight">new password</label>
          <%= f.input :password, label: false, required: false %>
        </div>
        <div class="col-12 col-sm-4">
          <label for=":password_confirmation">confirm new password</label>
          <%= f.input :password_confirmation, autocomplete: "off", label: false, required: false %>
        </div>
      </div>
      <% else %>
      <div class="row small-font opacity">
        <div class="col-12 col-sm-6">
        <label for=":weight">password</label>
          <%= f.input :password, label: false, required: false %>
        </div>
        <div class="col-12 col-sm-6">
          <label for=":password_confirmation">confirm password</label>
          <%= f.input :password_confirmation, autocomplete: "off", label: false, required: false %>
        </div>
      </div>
      <% end %>
    </div>

    <%  if current_user %>
      <div class="form-actions text-center">
        <%= f.button :submit, 'Update', class: 'btn btn-primary btn-update' %>
      </div>
      <div class="text-center">
        <br>
        Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
      </div>
    <% else %>
      <div class="form-actions text-center mt-3">
        <%= f.button :submit, 'Sign up', class: 'btn btn-primary btn-form' %>
        <br>

      </div>
    <% end %>
  <% end %>
<% end %>

<%= content_for :after_js do %>
  <%= javascript_pack_tag "uploader_btn" %>
<%end%>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed" id="nav_bar">
  <%= link_to 'STAKLE', root_path, class: 'navbar-title' %>


  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <% if current_user.devices.size == 0 %>
        <% url = "https://sportgeek.herokuapp.com/auth/fitbit_oauth2" %>
        <% if Rails.env == "development" %>
          <% url = "http://localhost:3000/auth/fitbit_oauth2" %>
        <% end %>
        <% Device.create(user_id: current_user.id, name: 'Fitbit device of the user #{current_user.id}') %>
         <% url = "https://sportgeek.herokuapp.com/auth/fitbit_oauth2" %>
        <% if Rails.env == "development" %>
          <% url = "http://localhost:3000/auth/fitbit_oauth2" %>
        <% end %>
        <%= link_to 'Dashboard', url, class: 'navbar-text' %>
      <% elsif DataPoint.where(date: DateTime.now.strftime('%Y-%m-%d')).size == 0 %>
        <% url = "https://sportgeek.herokuapp.com/auth/fitbit_oauth2" %>
        <% if Rails.env == "development" %>
          <% url = "http://localhost:3000/auth/fitbit_oauth2" %>
        <% end %>
        <%= link_to 'Dashboard', url, class: 'navbar-text' %>
      <% else %>
        <%= link_to "Dashboard", goals_path, class: "navbar-text" %>
      <% end %>
      <%= link_to "Profile", edit_user_registration_path, class: "navbar-text" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-text" %>
    <% else %>
      <!-- <button type="button" class="btn btn-primary btn-sm"><%= link_to 'Go for it', new_user_registration_path, class: "link-button" %></button> -->
      <%= link_to 'Log in', new_user_session_path, class: "navbar-text" %>
    <% end %>
  </div>
</div>

app/views/shared/_tabs.html.erb
<!-- <ul class="nav nav-pills nav-fill"> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link"><%= link_to goals_path do %> -->
<!--     Goals <%end%></a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link"><%= link_to tiers_path do %> -->
<!--     Tiers <%end%></a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link"><%= link_to rankings_path do %> -->
<!--       Rankings <%end%></a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link" href="#">Your profile</a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link" href="#">Your data</a> -->
<!--   </li> -->
<!-- </ul> -->
<!-- <ul> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link active" href="#">Active</a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link" href="#">Link</a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link" href="#">Link</a> -->
<!--   </li> -->
<!--   <li class="nav-item"> -->
<!--     <a class="nav-link disabled" href="#">Disabled</a> -->
<!--   </li> -->
<!-- </ul> -->
<%= render 'shared/navbar' %>
<ul class="nav nav-fill justify-content-center">
  <li class="nav-item">
    <!-- <a class="nav-link active" id="home-tab" data-toggle="tab" href="/goals" role="tab" aria-controls="home" aria-selected="true">Goals</a> -->
    <%= link_to 'Goals', goals_path, class: "nav-link hover" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Tiers', tiers_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Rankings', rankings_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Profile', graph_path, class: "nav-link" %>
  </li>
</ul>